mysql:
  host: xxx.xxx.xxx.xx
  port: 3306
  username: diting
  password: diting
jwt:
  secret: diting
log:
  log_file_path: ./logs
  log_file_name: diting.log
minio:
  accessKey: xxx
  accessSecret: xxx
  endPoint: xxx.xxx.xxx.xxx:9000
  useSSL: false
redis:
  host: xxxx
  password: xxxxx
rocketmq:
  host: xxx.xxx.xxx.xxx:9000
  group: diting